name: adf-ci-cd

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Azure Login
      uses: Azure/login@v1.4.3
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      working-directory: ${{ github.workspace }}
      run: npm install
      
    - name: Validate ADF  
      working-directory: ${{ github.workspace }}
      run:   'npm run build validate ${{ github.workspace }}/adf-data /subscriptions/${{ vars.SUBSCRIPTION }}/resourceGroups/${{ vars.RESOURCEGROUP }}/providers/Microsoft.DataFactory/factories/${{ vars.ADFINSTANCE}}'
    - name: Validate and Generate ARM template
      if: github.ref == 'refs/heads/main'
      working-directory: ${{ github.workspace }}
      run: 'npm run build export ${{ github.workspace }}/adf-data /subscriptions/${{ vars.SUBSCRIPTION }}/resourceGroups/${{ vars.RESOURCEGROUP }}/providers/Microsoft.DataFactory/factories/${{ vars.ADFINSTANCE}} "ArmTemplate"'
    - uses: actions/upload-artifact@v3
      with:
        name: Publish Artifacts
        path: ${{ github.workspace }}/ArmTemplate    

  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_TEMPLATE_FILE: ${{ github.workspace }}/ArmTemplate/ARMTemplateForFactory.json
    strategy:
      matrix:
        stage: ['Dev', 'QA']
      fail-fast: true
      max-parallel: 1
    environment:
      name: ${{ matrix.stage }}
      
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 

    #Disable Triggers
    - name: Run Pre-deployment script
      shell: pwsh
      run: pwsh -command "./PrePostDeploymentScript.ps1 -armTemplate ${{ env.ARM_TEMPLATE_FILE }}  -ResourceGroupName ${{ vars.RESOURCEGROUP }} -DataFactoryName ${{ vars.ADFINSTANCE }} -predeployment $true -deleteDeployment $false"
      
    - name: Deploy ADF ARM Templates ${{ matrix.stage }}
      uses: Azure/arm-deploy@v1
      with:
        scope: 'resourcegroup'
        resourceGroupName: ${{ vars.RESOURCEGROUP }}
        template: ${{ env.ARM_TEMPLATE_FILE }}
        deploymentMode: Incremental
        parameters: 
          factoryName=${{ vars.ADFINSTANCE }}
    
    #Enable Triggers
    - name: Run Post-deployment script
      shell: pwsh
      run: pwsh -command "./PrePostDeploymentScript.ps1 -armTemplate ${{ env.ARM_TEMPLATE_FILE }} -ResourceGroupName ${{ vars.RESOURCEGROUP }} -DataFactoryName ${{ vars.ADFINSTANCE }} -predeployment $false -deleteDeployment $true"
